id: segment_introduction
learningObjectives: 
- Learn what Segment is and set it up to work with your website
hints:
- "Sign up here: https://app.segment.com/signup"
- "Don't worry, you won't be charged for anything. Segment is completely free unless you have more than 10,000 identified users in a month, or unless you contact their sales team to unlock extra capabilities."
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "The first thing for you to start on is connecting our website to Twilio Segment."
      - text: "Segment is a Customer Data Platform.  Think of it like a bus for event streams, with some superpowers."
      - text: "In addition to collecting the trackable events from your various marketing channels, it identifies the user who performed the event and combines all of their event history into a profile that you can use to understand them better."
      - text: "Your first step is to create a free Segment workspace [here](https://app.segment.com/signup)."
      - text: "Once you've created your account, :instruction[come back here and let me know when you're ready to continue.]"
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Great, let's proceed."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "I'm here, just let me know when you're ready to continue."
