id: segment_token
learningObjectives: 
- Learn how to get your Segment API token
hints:
- "To create a new source, go to "Connections" in the Segment menu and then choose Sources.  You can add a new source from there."
- "Select your source type - **Javascript website** - as the type of source and click on **Create source**."
- "Your token should be a 32 character string, like this: `a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6`"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Now that you have a Segment account, let's create a new source. A source is a place where you can collect data about your users. In our case it'll be our website."
      - text: "So let's go over to the Segment dashboard and create a new Javascript website source. Once you have it, you'll be able to get your write token."
      - text: "Once you have your write token, :instruction[paste it here for me]."
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: ".*[a-zA-Z0-9]{32}.*"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Yep, that works! Now that you have your API token, let's establish the first call from the website to Segment."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Hmmm, that doesn't look like a valid API token. Try again."
