id: segment_destination
learningObjectives: 
- Learn how to connect source to destination in Segment

hints:
- "To connect a destination to your Segment workspace, look in Connections and choose 'Destinations' from your Segment workspace menu."
- "Segment asks for an API Key and an Account Secret.  You can find them on the Project Settings menu of your Mixpanel account."
- "Make sure you activate the destination in Segment, or the data won't flow to it!"
- "You can use the Event Delivery dashboard in Segment (located inside the Destination) to see whether events are flowing."
- "Look on the Events tab in Mixpanel to see whether they're received."

startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "OK, we have a source and some events, but we now need to connect it to a destination."
      - text: "A destination is a place where you can send your data, like Google Analytics, Amplitude, or Mixpanel. You can even use simple serverless function as a destination and host it directly within a paid Segment plan."
      - text: "For our purposes today, we're going to connect the site to Mixpanel. If you don't already have one, request a [free account](https://mixpanel.com/register/) on Mixpanel's site."
      - text: "Then create a Segment destination and get the data to flow to Mixpanel from the website."

trigger:
  type: user_event
  params: 
    event: segment_destination
  flowNode:
    do:
    - actionId: bot_message
      params:
        person: keen
        messages:
        - text: "Excellent work.  You can now see events generated in our website travel all the way through Segment to Mixpanel.  While this may not seem very efficient for a single destination tool, keep in mind that we have many tools in our stack that all need this same data.  Implementing each of them will be simple with Segment already connected."
    - actionId: finish_step
